; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.53"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[adminrole][subdir] = "contrib"
projects[adminrole][version] = "1.1"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "3.1"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.7"

projects[master][subdir] = "contrib"
projects[master][version] = "2.0-beta4"

projects[slack][subdir] = "contrib"
projects[slack][version] = "1.6"

projects[stage_file_proxy][subdir] = "contrib"
projects[stage_file_proxy][version] = "1.7"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.

projects[bootstrap][subdir] = "contrib"
projects[bootstrap][version] = "3.5"
